### ISSUE TITLE
Incorrect Compound Component Style

### ISSUE THREAD

**Issue by SoYoung210** [stitchesjs/stitches#1031]
# Bug report

## Describe the bug

It seems that the [styled](https://stitches.dev/docs/api#styled) is not immutable.

If a component is created with the same name by referencing the same module within one project, the styles of components with different styles are applied.

## To Reproduce

[Please see this sandbox.](https://codesandbox.io/s/stitches-style-issue-repro-3ndy8p?file=/src/App.js)

A Title component with `color: blue` style applied exists in `Dialog` component, and Title component with `color: green` style applied to `AnotherDialog` exists.

**"exists"** means that `Dialog.Title = Title`, and the component is assigned as a property called Title.

The color of `Dialog.Title` should be blue and the color of AnotherDialog.Title should be green, but both components are applied as green.

If this is an intended, I'd like to know what I'm missing.

## Expected behavior

`color: blue` should be applied to `Dialog.Title`, and `color: green` should be applied to `AnotherDialog.Title`.

## Screenshots

<img width="781" alt="image" src="https://user-images.githubusercontent.com/18658235/172158519-5fd2b2d3-086c-4cf9-8f53-f8433558a717.png">

<img width="708" alt="image" src="https://user-images.githubusercontent.com/18658235/172159388-cbd415cc-d9bc-41ac-b433-64ae2ecdbf7b.png">

## System information

- OS: macOS 12.2.1
- Browser: chrome
- Version of Stitches: 1.2.8
- Version of Node.js: 16.14.0

**Comment by hadihallak** [comment]
@SoYoung210 Thanks for submitting this issue. This is for sure not intentional 🤔 
To help us debug the issue, would you be able to create a simpler reproduction that doesn't use any external node_modules other than Stitches?

**Comment by SoYoung210** [comment]
@hadihallak I'll try it.
it may take some time because it cannot be reproduced immediately. 🧐
(IMO it's **not** a radix-ui problem.)

**Comment by rob-gordon** [comment]
@SoYoung210 I think this issue is because in both Dialog files you are adding your styled component as a property of the same object. Even though you use a variable, it's still pointing to the same import.

In other words, this:
```
const AnotherDialog = DialogPrimitive.Root;
AnotherDialog.Title = StyledTitle;
```
overrides this:
```
const Dialog = DialogPrimitive.Root;
Dialog.Title = StyledTitle;
```
because they're both effectively saying:
```
DialogPrimitive.Root.Title = StyledTitle
```


If you have a look at how radix-ui exports subcomponents from their design system (which uses stitches) you'll see that, for styling components, they export new components with a similar name, rather than adding them to the object

https://github.com/radix-ui/design-system/blob/6025f2e52be77dbef179029fc6b1d306b17cdc17/components/Dialog.tsx#L59-L71

Here's a fork of your repo following radix-ui's pattern with the issue fixed

https://codesandbox.io/s/stitches-style-issue-repro-forked-3sed7w?file=/src/Dialog.jsx

**Comment by SoYoung210** [comment]
@rob-gordon  

```
DialogPrimitive.Root.Title = StyledTitle
```

Oh, I missed this part. Thanks for the kind explanation.
