### ISSUE TITLE
Is stitches being maintained?

### ISSUE THREAD

**Issue by jessekrubin** [stitchesjs/stitches#1096]
I am just curious is stitches is under active development and is being maintained still. It doesn't look like there has been much activity on this repo/project for several months now.

**Comment by diegosilvadigital** [comment]
Hello @jessekrubin. Join the community on Discord, support there is much faster. Here's a position about your question.

![image](https://user-images.githubusercontent.com/38539443/193964638-3daed5b4-ae5f-4449-a550-23c8c5ad162a.png)

**Comment by mstade** [comment]
That's a bit of a non-answer though isn't it? Not investing time in new features is one thing, it's perfectly fair and fine to consider something finished. keeping an eye on bugs doesn't say anything about actually fixing them, but what's more important I feel is – what's the position on contributions?

It's unreasonable to expect too much from a free (as in beer) project, but what's the position on contributions? I'd be happy to contribute bug fixes and even new features, but that assumes the stewards of this project are interested in that. There's very little point in contributing code that's just going to languish in PR purgatory indefinitely. The comment in the linked screenshot seems to suggest such interest is limited, based on the presumption that "[we're] not investing dev time in new features" also means "[we're] not investing time in considering contributions".

If there's limited interest in investing time beyond the occasional bug fix, then is there any interest in handing over stewardship of the stitches project to people that are interested in taking it forward?

**Comment by jakubzet** [comment]
Also, I think the library is wonderful - especially with it's approach to theming, TypeScript integration and overall DX. Yet, I'm a little but concerned about the future of CSS-in-JS overall - as the arguments within that articles states: [https://dev.to/srmagura/why-were-breaking-up-wiht-css-in-js-4g9b](https://dev.to/srmagura/why-were-breaking-up-wiht-css-in-js-4g9b). Perhaps there's the shift coming and the authors already have this in minds? I'm not sure how many of those probles also touches Stitches, though.

**Comment by mstade** [comment]
@jakubzet yes there definitely seems to be some of that involved.

It's a sad state of affairs though, when a single post from a single developer of a single UI framework seem to more or less kneecap an entire cottage industry of quite excellent developer tools. The rumors that CSS-in-JS is dead I would say are greatly overblown, and stem from this particular detail, as quoted from the post:

> In concurrent rendering, React can yield to the browser between renders. If you insert a new rule in a component, then React yields, the browser then have to see if those rules would apply to the existing tree. So it recalculates the style rules. Then React renders the next component, and then that component discovers a new rule and it happens again.
>
> This effectively causes a recalculation of all CSS rules against all DOM nodes every frame while React is rendering. This is VERY slow.
>
> <https://github.com/reactwg/react-18/discussions/110>

This has more to do with how React renders things _in concurrent mode_ than CSS-in-JS being a fundamentally bad idea. If you're not using streaming then this doesn't really apply. Even if you are, the React team were at least nice enough to provide an escape hatch for CSS-in-JS libs: the `useInsertionEffect` hook. I've used this with stitches, and it does seem to do what it says on the tin.

The rest of the arguments in the article you linked are tenuous at best I'd say, and mostly boil down to preference – which is ok! But preferences turning into industry wide dogma is sad face times.

Coming back to stitches – I believe it should be possible to transition stitches so it's able to both precompile styles OR provide them at runtime, and that seems like a viable path to me going forward. I've been reading the source of this project and it's clear to me that this is a _very_ high quality project – big kudos to the authors, they are obviously _very_ competent people! – and it'd be a shame to throw the baby out with the bathwater just because the React team makes... interesting choices.

I've rewritten an app of mine to use stitches instead of styled-system, and the DX and resulting code are both _glorious_. I'd be willing to put in some time whenever I'm able to contribute patches to this project, bug fixes _and_ features alike, because it's an oh-so-nice project and I'd like to keep using it. But not without first knowing that the maintainers will actively entertain such contributions. If it's a black hole the the options are to either fork or keep moving and sadly, I don't have time to maintain a fork.

**Comment by jakubzet** [comment]
@mstade - looks like we share the same opinion :) That would be such a waste to give up on such a great foundation. I haven't dove into the details yet, but there are - as you mentioned - pre-compiled CSS-in-JS libraries such as Linaria. Checking if implementing such mode for Stitches would be possible would be definitely interesting both for users and authors I guess - surely sounds like a direction of further development.

**Comment by gajus** [comment]
For what it is worth, https://github.com/contra team heavily relies on Stitches, and if a decision was made by Stitches team to deprecate the library, we would be the first in line to volunteer taking it over.

CC @peduarte @jon_neal @hadi_hlk just so this is on your radar

**Comment by jpmaga** [comment]
> For what it is worth, [@contra](https://github.com/contra) team heavily relies on Stitches, and if a decision was made by Stitches team to deprecate the library, we would be the first in line to volunteer taking it over.
> 
> CC @peduarte @jon_neal @hadi_hlk just so this is on your radar

@gajus any word on this so far? This would be an interesting turn of events.

PS: I've used slonik on a couple projects and really liked it, so I am confident the result with stitches would be top notch as well.

**Comment by StephenHaney** [comment]
Hey all, please come discuss in #1144 

@gajus I'll shoot you a message if you're interested in chatting more on this.
