### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by zRelux** [stitchesjs/stitches#596]
I really love what you guys have been doing with stitches  and have been loving it so far!

Any idea if react native is in the roadmap, I think the community would benefit a lot from this

**Comment by Temzasse** [comment]
Hi 👋🏻 

I've been working on the RN version of Stitches here: https://github.com/Temzasse/stitches-native

The core functionality is pretty much ready but I'm quite badly stuck with the TS typings. Any help with the typings would be very much welcome! 👐🏻 

@peduarte do you have any tips about how could I utilize the existing types of Stitches in the RN version? I see that you have gone the declaration route instead of adding types to the implementation itself. I've been trying to type the implementation in my version and it gets super tricky 😄  Would you be open to sharing the learnings of your TS journey with Stitches?

**Comment by peduarte** [comment]
@Temzasse hi! Nice 💯 

> utilize the existing types of Stitches in the RN version?

We're currently working on a TS specific sprint. Expect lots of TS changed over the next few weeks. Right now, I cant recommend anything, because its likely everything will change. 

When we release the new TypeScript work, I'll post an update here!

**Comment by csantos-nydig** [comment]
FYI: I believe this is the TS PR Pedro referred to: https://github.com/modulz/stitches/pull/659 👀

**Comment by Temzasse** [comment]
Uuuh nice! 👍🏻 I'll take a look 👀 

I actually managed to get the TypeScript part working with the current typings from Stitches repo by copy-pasting them into my repo and modifying the types to work with React Native.

I still need to write some docs for React Native specific stuff and test the lib more (and maybe write some actual tests 🙈) and then I would be ready to publish the first version of `stitches-native` so that people can try it out 🙂

**Comment by jonathantneal** [comment]
The TS sprint was a success and we have since launched v1.0.0. Does this work for `stitches-native`, @Temzasse. Should we close this?

**Comment by csantos1113** [comment]
Hey @jonathantneal - do you have any near plans to support react-native as part of modulz directly? `stitches-native` from @Temzasse is a really good starting point, but would be nice to have support for both out of the box!
imagine: `@stitches/core` , `@stitches/react`, `@stitches/react-native` 😍

**Comment by Temzasse** [comment]
@jonathantneal I haven't had the time to incorporate the updated typings from v1 yet but I'll try to get it done as soon as possible. There are a few other smaller things that also need to be implemented in `stitches-native` but we should be quite close to the initial release 🤞🏻 

Maybe we can keep this issue open until the first proper release of `stitches-native` is out? (there is a pre-release out already so that I was able to reserve the name on npm 😄)

**Comment by nandorojo** [comment]
@Temzasse one issue I see with the implementation is that it doesn't use dynamic window dimensions for media queries. Since RN doesn't have native breakpoints, this would be required via a hook. It's what we use for Dripsy. As a result, changing screen size won't update styles. Have you considered a way around this?

**Comment by Temzasse** [comment]
## Stitches Native TS update

@jonathantneal I got the new Stitches v1 types working in Stitches Native apart from one issue in RN specific `ThemeProvider` that I haven't yet figured out (slapped an `any` to it for now since it doesn't really affect the DX).

There is a new pre-release version that people can try out: `npm install stitches-native@canary`

## Next steps

I still need to comb through the Stitches API and verify that I'm not missing anything important in Stitches Native.

One thing that I know is still missing is the composability of `css` and `styled` thingies, eg:

```ts
const sharedCssA = css({ /* styles */ });
const sharedCssB = css({ /* styles */ });

const CompA = styled('View', sharedCssA, sharedCssB);
const CompB = styled('View', CompA);
```

Stitches Native currently only supports the simple version of composing `styled` components: 

```ts
const CompA = styled('View', { /* styles */ });
const CompB = styled(CompA, { /* styles */ });
```

Not sure if it's enough that you are able to spread as many `css` objects inside a `styled` object 🤔 

```ts
const cssA = css({
  backgroundColor: '$background',
});

const cssB = css({
  alignItems: 'center',
  justifyContent: 'center',
});

const Comp = styled('View', {
  flex: 1,
  ...cssA,
  ...cssB,
});
```

I guess the drawback is that you can't really use `variants` etc since the last one would overwrite the previous ones.

**Comment by Temzasse** [comment]
@nandorojo could you open an issue about this in the Stitches Native [repo](https://github.com/Temzasse/stitches-native/issues) so that we could discuss this topic there? 🙂 

> @Temzasse one issue I see with the implementation is that it doesn't use dynamic window dimensions for media queries. Since RN doesn't have native breakpoints, this would be required via a hook. It's what we use for Dripsy. As a result, changing screen size won't update styles. Have you considered a way around this?

**Comment by jonathantneal** [comment]
I’m unsure if we should leave this open, direct the discussion to [stitches-native](https://github.com/Temzasse/stitches-native), or seek to merge **stitches-native** into our repository. I’d like to hear your ideas, @Temzasse, before knowing what action to take here.

**Comment by nandorojo** [comment]
@Temzasse will do. One other suggestion is not not allow the `styled` function to accept strings. This would break tree shaking, causing of all of RN to import, especially on web.

**Comment by LucasUnplugged** [comment]
> I’m unsure if we should leave this open, direct the discussion to [stitches-native](https://github.com/Temzasse/stitches-native), or seek to merge **stitches-native** into our repository. I’d like to hear your ideas, @Temzasse, before knowing what action to take here.

My 2 cents: if the core Stitches team is willing to merge `stitches-native`, that might be less responsibility on one person's shoulders, and probably better for consumers of the lib as well.

Can't wait to try Stitches with RN, either way! Thanks @Temzasse !

**Comment by axeldelafosse** [comment]
Yes! I think it's a good idea to merge. Thank you for considering it!

**Comment by Temzasse** [comment]
> I’m unsure if we should leave this open, direct the discussion to [stitches-native](https://github.com/Temzasse/stitches-native), or seek to merge **stitches-native** into our repository. I’d like to hear your ideas, @Temzasse, before knowing what action to take here.

I'm definitely open to any of the above 👍🏻 

@LucasUnplugged had a good point that merging **stitches-native** to the main Stitches repo would help reduce some of the maintenance burden from me, and in the future it would be easier to have both Stitches for Web and Stitches for React Native evolve hand in hand without too much divergence.

However, I'm also happy keeping **stitches-native** as a separate project and you can direct any discussion to [stitches-native repo](https://github.com/Temzasse/stitches-native). In any case It would be cool to get more contributors aboard in order to make it a more community driven effort 🙂 

Here are some pros and cons for the merging idea that came to my mind:

Pros:
- Better documentation (if RN specific docs can be included in stitches.dev)
  - Also better discoverability since Stitches is already making a name in the CSS-in-JS land
- More trust from devs (official solution vs. 3rd party solution)
- Keeping TS types up-to-date would be much easier (this is a big one for me 😄)
- Possibility to get help with the implementation from the Stitches core team

Cons:
- Forcing Modulz to take responsibility of something that is not part of their core product (I'm under assumption that you don't do any RN stuff?)
- Burdening Modulz with RN specific issues that would make the maintenance of stitches more challenging and laborious

**Comment by Temzasse** [comment]
## Stitches Native update

- Fixed the lack of composability in `css` and `styled`
- Updated the docs about [supported token types](https://github.com/Temzasse/stitches-native#supported-token-types)
- Published a new [canary version](https://www.npmjs.com/package/stitches-native/v/0.0.1-3)

### The way forward

@jonathantneal have you and the rest of the team had the opportunity to think about the idea of merging Stitches Native into the Stitches repo?

I feel like Stitches Native is now ready for wider usage. There are still things to do like writing tests (🙈) and refining the docs but the core functionalities should be pretty much in place (unless I have missed something).

One challenge that I have is that I'm not currently able to dog food Stitches Native at my company or in side project so it's difficult to make sure that there are no unhandled edge cases. I'm considering publishing `0.1.0` version (or maybe even `1.0.0`) on npm to encourage people to install and try out Stitches Native.

**Comment by mtt87** [comment]
OT: @nandorojo I didn't know your library, looks interesting I'll check it out 😄  thank you

**Comment by Temzasse** [comment]
@mtt87 Thank you for your feedback 🙏

Here's my response to the various topics:

TypeScript

- The types are definitely the hardest part of the library implementation and there is definitely improvements to be made. However, I think it's important to note that the way theme tokens are referenced in Stitches via magic strings is inherently unsafe (unless you use the theme object directly) so I feel like that is a tradeoff that one has to just accept if you want to take advantage of the "magic".
- Fixing React Native specific issues like the `fontWeight` (which can cause hard crashes) is definitely something we want to fix, but I don't think handling things like `lineHeight` difference between Web and Native is the concern of the library. There are other platform differences such shadows that also need to be handled differently so my view is that those kind things should be left to the user to handle (for shadows Stitches Native already provides a `utils` based solution example in the docs).

Nesting/selectors

- This is also another limitation that I think just has to be accepted. I understand the pain of not being able to style child components within the parent via selectors - I have many times wished that it would be possible 😁
- You are right that the power of compound variants is not as great in RN as it is in the Web. Did you have any ideas how we could make this better and more suitable for RN? I wouldn't want to diverge from the Stitches API too much but if there is a much better way to handle some aspect it might make sense to create a RN specific API for it.

In a perfect world there would be an universal styling library that would map 1-1 between Web and Native but I think that is not practically feasible due to the inherent differences between the platforms. I totally understand that when creating design systems / component libraries it would be nice to share as much as possible but I feel like the sharing part should mostly happen at the design token level. Implementing shareable components will probably lead to an implementation that is not optimized for either platform. Sorry if this sounds harsh - I just wanted to share my philosophy about this subject 😅

**Comment by nandorojo** [comment]
I like the discussion here.

Here’s my take: we should embrace the way that React Native works, rather fit it to be like CSS.

Nested selectors and pseudo elements give you convenience, but don’t scale well for a component-based design system. I think it’s actually a good limitation of React Native to not have these.

I recommend this talk from the creator of React Native for Web, it really solidified that perspective for me: https://youtu.be/tFFn39lLO-U

I’ll also be talking about this topic at Next.js Conf in a few days: https://nextjs.org/conf/speakers/fernando

> In a perfect world there would be an universal styling library that would map 1-1 between Web and Native but I think that is not practically feasible due to the inherent differences between the platforms.

I agree, but the baseline for these styles should be React Native’s styling system, not CSS. If that’s the case, then we can in fact get the 1-1 mapping. React Native’s styling system lends itself to work well on web. CSS, on the other hand, is too low level and coupled to HTML to be used on other platforms.

I’m not sure what the right answer is in the case of porting Stitches and its variants, but I think we can take the best of stitches, and still lean into React Native (+ Web)’s styling philosophy. 

I came to this conclusion after using Dripsy in production for [beatgig.com](https://beatgig.com) for about a year, where my original goal was also to copy all the CSS options from theme UI.

I hope that makes sense.

**Comment by mtt87** [comment]
I didn't look at the codebase but all these styling properties are already correctly typed 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L932
Shouldn't stitches-native somehow extend these types?

**Comment by justindomingue** [comment]
@peduarte any official update from the dev team on this ?

**Comment by hadihallak** [comment]
Hey everyone 👋 
We don't currently have plans to add official react-native support.
@Temzasse The `stitches-native` does look very promising and I really like how well you're documenting the API so I'd be very happy to merge a PR to add it to the list of [community built packages](https://github.com/stitchesjs/stitches#community)

**Comment by Temzasse** [comment]
@hadihallak here's the [PR](https://github.com/stitchesjs/stitches/pull/1033) 😉
