### ISSUE TITLE
What's the purpose of the object returned from `css`?

### ISSUE THREAD

**Issue by lukemorales** [stitchesjs/stitches#928]
I was creating custom styles with `css` function and to make my life easier I'm using `clsx` to merge a lot of classNames, but just following the documentation of calling the result of `css` within `clsx` things did not work as expected and I noticed some weird classes being added such as `type toString`.

When calling the result of `css` in a `console.log` I got this object:
```js
{
  "type": "span",
  "className": "c-egYIFi",
  "selector": ".c-egYIFi",
  "props": {
    "className": "c-egYIFi"
  },
  "deferredInjector": null,
  "toString": fn
}
```

This is not documented anywhere in the DOCS and it also cannot be rendered as a React Component, so what would be the purpose of this object, and why is the documentation only saying `A function to generate class names from a style object.` which can be misleading as it's giving the impression of just returning a string?

**Comment by baryla** [comment]
I'm going to take a guess and assume that the point of the object is so that the library can track what `className` it has already generated and for more internal work under the hood. Also, I don't think the `css` object is meant to be used with `clsx`. This will work as expected if you use the `css` object as a value for the `className` like so: 
```tsx
const buttonStyles = css({
  color: 'red'
});

() => <button className={buttonStyles}>Hello</button>;
```

Now, because React/JSX expects `className` to be a string, it will internally convert the object aka. call the `toString` method on the object and return the `className` property of the object :) You can test this theory by simply logging the `css` object like so: 
```tsx
console.log(`${buttonStyles}`);
```

**Comment by lukemorales** [comment]
> I'm going to take a guess and assume that the point of the object is so that the library can track what `className` it has already generated and for more internal work under the hood. Also, I don't think the `css` object is meant to be used with `clsx`. This will work as expected if you use the `css` object as a value for the `className` like so:
> 
> ```tsx
> const buttonStyles = css({
>   color: 'red'
> });
> 
> () => <button className={buttonStyles}>Hello</button>;
> ```
> 
> Now, because React/JSX expects `className` to be a string, it will internally convert the object aka. call the `toString` method on the object and return the `className` property of the object :) You can test this theory by simply logging the `css` object like so:
> 
> ```tsx
> console.log(`${buttonStyles}`);
> ```

Makes sense, for the use of `clsx` I had to call `buttonStyles().className`, which is not a big deal, but as the documentation lacks some clarity on this I had to do some debugging to actually understand what was happening. Clarifying this can prevent others from experiencing the same thing
